#!/bin/sh
echo " "
echo "   ___  _   _ ___ _  _ ____ _  _ "
echo "   |__]  \_/   |  |__| |  | |\ | "
echo "   |      |    |  |  | |__| | \| "
echo " "
echo "    _  _ ____    ____ ____ _  _ "
echo "    |\ | |  |    [__  |___ |  | "
echo "    | \| |__|    ___] |___ |__| "
echo " "
echo "___  ____ ____ _ _ _ ____ ____ ____ "
echo "|__] |__/ |  | | | | [__  |___ |__/ "
echo "|__] |  \ |__| |_|_| ___] |___ |  \ "
echo " "
echo "Executar \"python3\" para modo interactivo"
echo " "
/bin/sh
